### PR TITLE
generic batch kron

### PR DESCRIPTION
**Pull request by Roger-luo**
this is more general and costs less memory, and should be possible be generated by SPMD in the future.

close #17

### CODE REVIEW

**Comment by Roger-luo** [comment]
actually I have no idea why I converted `Array` to pointers in the first place. The current version is much better than the original one.

**Comment by GiggleLiu** [comment]
stackoverflow error @Roger-luo

**Comment by Roger-luo** [comment]
It looks fine locally

**Comment by Roger-luo** [comment]
@GiggleLiu I'll merge this first to see if it works on master. I don't think the CI fails because of the implementation. we can revert it if the master CI doesn't pass.

**Comment by Roger-luo** [comment]
fixed by 578a7d63b015e056fe4523575e0ea559896bfb3a

**Pull request merged**
